development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://h:p0d4e491982e6a62730eef29ab01c51450fbebcbe4d5596817b96cd9316ca7c62@ec2-52-70-90-107.compute-1.amazonaws.com:18329
  channel_prefix: crier_production
